### ISSUE TITLE
time zone

### ISSUE THREAD

**Issue by SWE15041** [wso2-extensions/esb-connector-dayforce#6]
**Description:**
What are the time zones of API request parameters and return parameters? What is the default?

**API:**
https://developers.dayforce.com/Build/API-Explorer/Time-Management/GET-Employee-TAFW.aspx
https://developers.dayforce.com/Build/API-Explorer/Time-Management/Employee-Availability.aspx

**Affected Product Version:**
Release Version: 58

**Comment by anupama-pathirage** [comment]
Moved the issue to https://github.com/wso2/micro-integrator/issues/3471
